### ISSUE TITLE
nur ein TOP wenn Protokoll fehlt

### ISSUE THREAD

**Issue by sviatoplok** [sviatoplok/mrp-regeln#10]
Bei MRP wo 
1) das Protokoll fehlt:
2) es nur einen TOP gibt:
sollen wir auch da die Nummer I. in eckige Klammern geben?
Siehe Anhang.
![1](https://user-images.githubusercontent.com/46528983/64154027-4c938880-ce30-11e9-85f6-e4411709c6de.PNG)

**Comment by AnToMaAi** [comment]
Ich habe das bei dem Bank von Thomas eingefügt - trotz der Bemerkung von Stefan - weil wir es in der ersten Serie so gemacht haben. Einen Informationswert hatte es vorher auch nicht, außer für die Einheitlichkeit des Zitats: Datum/TOP. Und das trifft auch auf die verbrannten Protokolle zu.
