### ISSUE TITLE
Kopfregest Schreibweise Ah. E.

### ISSUE THREAD

**Issue by RdLein** [sviatoplok/mrp-regeln#11]
Unterschiedliche Schreibweise im Kopfregest -> Wortlaut und Datum der Ah. E. (Wladimir) bzw. Wortlaut und Datum der Ah. Entschließung (Stefan)

Welche nehmen wir?

**Comment by AnToMaAi** [comment]
Nachdem Stefans Band schon vorliegt, können wir es so machen wie Stefan oder ist das für Dich zu viel Arbeit, Wladimir?

**Comment by sviatoplok** [comment]
Hallo, nein, das konnen gerne so machen.
Es gilt also:
>Wortlaut und Datum der Ah. Entschließung
