### ISSUE TITLE
Zitierweise Staatsgrundgesetze

### ISSUE THREAD

**Issue by RdLein** [sviatoplok/mrp-regeln#12]
Welche RGBLs sind bei Kommentierung des Begriffs Staatsgrundgesetze anzugeben? 141 bis 147 oder nur das jeweils zu diesem Punkt sinngemäß gemeinte?

Falls alle anzugeben sind, wie hat die Korrekte zitation zu lauten? RGBl. 141/1867, 142/1867, 143/1867, 144/1867, 145/1867, 146/1867, 147/1867 oder 141-147/1867.

**Comment by sviatoplok** [comment]
Wie lautet die Antwort auf diese Frage?

**Comment by AnToMaAi** [comment]
Ich würde schreiben RGBl. Nr. 141 bis 147, alle ex 1867.
