### ISSUE TITLE
ermittelte Kalenderdaten auszeichnen

### ISSUE THREAD

**Issue by sviatoplok** [sviatoplok/mrp-regeln#14]
In einem Protokoll v. 27. 10. 1918 taucht der Satz auf:

> Der Minister für Kultus und Unterricht stellt fest, dass er dem Ministerpräsidenten schon am Donnerstag  seine Demission angemeldet habe.

Ich gebe nun händisch das Datum im ISO-Format in doppelten geschweiften Klammern ein, um es später strukturiert verwenden zu können:

> "Donnerstag`{{1918-10-24}}`"

**Comment by sviatoplok** [comment]
machen wir es so?

**Comment by AnToMaAi** [comment]
In Ordnung. Außerdem sollte dann in Situationen, in denen eine Erstnennung schon aber das konkrete Enddatum nicht bekannt ist ein notBefore eingefügt werden.
