### ISSUE TITLE
Abkürzungsverzeichnis zentral

### ISSUE THREAD

**Issue by skurzinz** [sviatoplok/mrp-regeln#17]
Idee: Word-Liste in strukturierte Daten, die dann in ein Konstrukt wie `<choice><abbr>HM.</abbr><expan>Handelsministerium</expan></choice>` transformiert werden.

**Comment by skurzinz** [comment]
liegt am Share in `Cisleithanien` : Abkürzungen-Zentral.docx

**Comment by sviatoplok** [comment]
Danke!

Alle Abkürzungen, die nicht in dieser Liste stehen, müssen also aufgelöst werden. In spezielen Fällen bitte Anfrage stellen.
