### ISSUE TITLE
wohin mit den Regeln etc.?

### ISSUE THREAD

**Issue by sviatoplok** [sviatoplok/mrp-regeln#2]
Lieber @skurzinz , wo lege ich am besten die Regeln an, bei den Issues oder bei Code oder gleich als ein Projekt?

es gäbe natürlich andere Lösunge als github wie zB Podio, aber nachdem das hier schon so viele nutzen, dachte ich, wäre es gut, die genutzten Plattformen zu minimieren.

**Comment by skurzinz** [comment]
hier ist eh gut
