### ISSUE TITLE
APIS Anlegen von Entities und Relationen

### ISSUE THREAD

**Issue by pSwoboda84** [sviatoplok/mrp-regeln#22]
Beim Anlegen von Entities passiert es immer wieder, dass ich keine Relationen (z.B. Label) eingeben kann und diese, nachdem ich die Entity angelegt habe auch nicht nachtragen kann.
Aufgefallen ist mir gerade eben: Wenn ich Personendaten aus dem GND importieren kann, dann kann ich auch Relationen anlegen. Wenn ich die Person gänzlich neu anlegen muss, dann geht es nicht.

**Comment by sviatoplok** [comment]
...und wenn du den Datensatz schließt (zB mit dem Auge) und wieder öffnest?

**Comment by sviatoplok** [comment]
...oder kannst du mir ein bestimmtes Beispiel nennen, damit ich es bei mir testen kann?

**Comment by pSwoboda84** [comment]
Sowohl beim Anlegen, als auch nach dem Schließen und darauffolgendem edit.

Hier zwei Beispiel
Bartels von Bartberg, Eduard (https://mpr.acdh.oeaw.ac.at/apis/entities/entity/person/7082/detail) --- funktioniert
Czaykowski, Jan (https://mpr.acdh.oeaw.ac.at/apis/entities/entity/person/7083/detail) --- funktioniert nicht.

**Comment by sviatoplok** [comment]
Bei mir gehen beide zu edieren.
![grafik](https://user-images.githubusercontent.com/46528983/73531646-2c85e680-441b-11ea-8283-51410f2268db.png)

**Comment by pSwoboda84** [comment]
Bei mir leider nicht:

![Screenschot](https://user-images.githubusercontent.com/60348223/73592793-45b39380-44fe-11ea-83d2-a091146a70e2.png)

**Comment by skurzinz** [comment]
Ich hab das zuerst auch ausprobiert und gesehen, dass ich beide Beispiele editieren kann; dann habe ich die Rechte für den PSwob in APIS noch ein Stück aufgebohrt und ich hoffe, dass es jetzt klappt. Bitte um Bestätigung...

**Comment by pSwoboda84** [comment]
Habs ausprobiert. Jetzt funktioniert es. Danke
