### ISSUE TITLE
Geonames kann nicht in APIS importiert werden

### ISSUE THREAD

**Issue by pSwoboda84** [sviatoplok/mrp-regeln#24]
So geschehen bei: Janče (Jantschberg)

Ich kann ihn auf geonames finden, aber nicht in APIS anlegen

**Comment by skurzinz** [comment]
<https://mpr.acdh.oeaw.ac.at/apis/entities/entity/place/7493/>

Der "Jantschberg" Eintrag auf Geonames ist nur ein Snippet, das auf Wikipedia verweist und worin keine Daten sind. Ich habe nochmal auf Geonames gesucht und http://www.geonames.org/3198900/jance.html gefunden, mit dessen RDF-Link gings dann in APIS.
