### ISSUE TITLE
Abk. Ing.

### ISSUE THREAD

**Issue by sviatoplok** [sviatoplok/mrp-regeln#5]
Abk. Ing. in die Abkürzungsliste? Ist ein Titel wie Dr.

**Comment by skurzinz** [comment]
Technisch ist das kein Problem, Ing. aufzunehmen. Siehe #17

**Comment by AnToMaAi** [comment]
Wenn im Text als Titel als Abkürzung aufnehmen. Z. B. Ministerpräsident Dr. Lammasch … EEbenso andere Titel. Daher gehören sie wohl in eine allgemeine Abkürzungsliste.
