### ISSUE TITLE
Auszeichnung von Ortsnamen in der TO

### ISSUE THREAD

**Issue by sviatoplok** [sviatoplok/mrp-regeln#9]
Sollen wir Ortsnamen, die in der TO vorkommen, mit dem PlugIn auszeichnen oder nicht?
Vorteil: bei verbrannten Protokollen wären wenigstens die ON im INdex dokumentiert, über die gesprochen wurde (gilt auch für PN und Institutionen).
Nachteil: eigentlich sind die Orte gar nicht Gegenstand der Edition, weil wir die Protokolle dazu ja nicht edifren, gehören also eigentlich nicht in den Index.

**Comment by AnToMaAi** [comment]
Wir habe bisher gesagt, wir verlinken nur vorhandene Protokolltexte, nicht die TOs.

**Comment by skurzinz** [comment]
+1; bei Volltextsuche tauchen die Ortsnamen dann ohnehin auf (wenngleich nur in der verwendeten Schreibung), im Zweifelsfall ist der Verlust nicht groß, weil ja ohnehin kein Protokolltext da ist.
